name: Check App Versions

on: workflow_dispatch

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  
  Check-Versions-Linux:
    name: Run Version Checks
    runs-on: ubuntu-latest
    steps:
      
      - name: Check Packer Version
        shell: pwsh
        run: |
          Write-Warning "Checking Packer Version"
          packer --version
      
      - name: Check Terraform Version
        shell: pwsh
        run: |
          Write-Warning "Checking Packer Version"
          terraform --version
  
  Check-Versions-Windows:
    name: Run Version Checks
    runs-on: windows-latest
    steps:
      
      - name: Check Packer Version
        shell: pwsh
        run: |
          Write-Warning "Checking Packer Version"
          packer --version
      
      - name: Check Terraform Version
        shell: pwsh
        run: |
          Write-Warning "Checking Packer Version"
          terraform --version
